name: hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hassfest:
    name: Hassfest
    runs-on: "ubuntu-latest"
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: "actions/checkout@v3"

      - name: 🚀 Run hassfest validation
        uses: home-assistant/actions/hassfest@master